replicaCount: 1
revisionHistoryLimit: 1
image:
#  repository: registry.baloise.dev/example/nginx-sample
#  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
serviceAccount:
  create: true
  name:
  automountServiceAccountToken: false
  annotations: {}
network:
  http:
    servicePort: 8080
#    ingress:
#      host: demo-app.apps.example.tld
service:
  type: ClusterIP
  annotations: {}
ingress:
  controller: Route
deployment:
  strategy:
    type: RollingUpdate
env: []
envFrom: []
persistence:
  enabled: false
  accessModes: ReadWriteOnce
#  storageClass: "ceph"
  annotations: {}
#  size: 1Gi
#  volumeMount: /var/app/data/
volumes: []
volumeMounts: []
readinessProbe: {}
#  httpGet:
#    path: /
#    port: http
livenessProbe: {}
#  httpGet:
#    path: /
#    port: http
resources: {}
tlsSidecar:
  enabled: false
  image:
    repository: docker.io/envoyproxy/envoy
    tag: v1.14.4
    pullPolicy: IfNotPresent
  upstreamPort: 8080
  httpsPort: 8443
  resources:
    requests:
      memory: 32Mi
      cpu: 20m
    limits:
      memory: 32Mi
      cpu: 100m
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
defaultAffinityRules:
  enabled: true
annotations: {}
labels: {}
command: []
args: []