replicaCount: 2
revisionHistoryLimit: 1
image:
  repository: quay.balgroupit.com/example/nginx-sample
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  zone: ch
  path: /
  annotations:
    haproxy.router.openshift.io/timeout: 5m
env:
  - name: DEMO_VARIABLE
    value: "Demo Variable"
envFrom: []
persistence: {}
volumes: {}
volumeMounts: {}
# e.g. multiple Volumemounts
volumeMounts:
      - mountPath: /usr/local/sometool
        name: mytool
      - mountPath: /var/log/something
        name: mysomething
      - mountPath: /etc/nginx/nginx.conf
        name: nginx-conf
        subPath: nginx.conf
readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 1
livenessProbe: {}
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 32Mi
nodeSelector: {}
tolerations: []
affinity: {}
defaultAffinityRules: {}
annotations: {}