replicaCount: 2
revisionHistoryLimit: 1
image:
  repository: registry.baloise.dev/example/nginx-sample
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
podSecurityContext: {}
securityContext: {}
serviceAccount:
  create: true
  name:
  automountServiceAccountToken: true
network:
  api:
    servicePort: 8080
    ingress:  {}
  mgmt:
    servicePort: 9090
    ingress:
      host: app.example.tld
      annotations:
        haproxy.router.openshift.io/timeout: 5m
ingress:
  zone: ch
service:
  type: ClusterIP
env:
  - name: DEMO_VARIABLE
    value: "Demo Variable"
envFrom: []
persistence:
  name: data
  storageClass: custom-storage-class
  enabled: true
  accessModes: ReadWriteMany
  size: 100Mi
  volumeMountPath: /app/data
volumes:
  - name: config-volume
    configMap:
      name: special-config
volumeMounts:
  - mountPath: /usr/local/sometool
    name: special-config
  - mountPath: /var/data
    name: data
readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 1
livenessProbe: {}
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 32Mi
nodeSelector: {}
tolerations: []
affinity: {}
defaultAffinityRules: {}
annotations: {}
command:
  - /app
  - --debug
