replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

route:
  enabled: false
#  host: demo-app.chapp-test.os1.balgroupit.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
