replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: quay.balgroupit.com/example/nginx-sample
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  zone: ch
  path: /
env:
  - name: DEMO_VARIABLE
    value: "Demo Variable"
envFrom:
  - configMapRef:
      name: demo-cm
persistence:
  enabled: true
  name: DemoPVC
  accessModes: ReadWriteOnce
  storageClass: trident-nfs-snapshot
  size: 1Gi
  volumeMountPath: /var/app/data/
volumes:
  - name: config-volume
    configMap:
      name: demo-cm
volumeMounts:
  - name: demo
    mountPath: /var/demo/data
readinessProbe:
  httpGet:
    path: /
    port: http
livenessProbe:
  exec:
    command:
      - /bin/bash
      - '-c'
      - timeout 60 /opt/app/bin/livenessProbe.sh
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 1.5Gi
nodeSelector: {}
tolerations: []
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - redis
        topologyKey: "kubernetes.io/hostname"
defaultAffinityRules:
  enabled: true
annotations: {}