replicaCount: 2
revisionHistoryLimit: 1
image:
  repository: quay.balgroupit.com/example/nginx-sample
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
podSecurityContext: {}
securityContext: {}
initContainers:
  - name: "demo-init-container"
    image: quay.balgroupit.com/baloise-base-images/busybox:1.31.1
    command: ["sh","-c", "echo test"]
    volumeMounts:
      - name: special-config
        mountPath: /tmp
    env:
      - name: INIT_DEMO_VARIABLE
        value: "Init Demo Variable"
serviceAccount:
  create: true
  name:
  automountServiceAccountToken: true
network:
  api:
    servicePort: 8080
    ingress:
      host: example-url.tld
  mgmt:
    servicePort: 9090
    ingress:
      host: abcz-chapp-balgroupit.com
      annotations:
        haproxy.router.openshift.io/timeout: 5m
service:
  type: ClusterIP
env:
  - name: DEMO_VARIABLE
    value: "Demo Variable"
envFrom: []
persistence:
  name: data
  storageClass:
  enabled: true
  accessModes: ReadWriteMany
  size: 100Mi
  volumeMountPath: /app/data
volumes:
  - name: special-config
    configMap:
      name: special-config
volumeMounts:
  - mountPath: /usr/local/sometool
    name: special-config
  - mountPath: /var/data
    name: data
readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 1
livenessProbe: {}
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 32Mi
nodeSelector: {}
tolerations: []
affinity: {}
defaultAffinityRules: {}
annotations: {}
enableReloader: true