replicaCount: 1
revisionHistoryLimit: 1
zone: any
image:
#  repository: quay.balgroupit.com/example/nginx-sample
#  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
serviceAccount:
  create: true
  name:
  automountServiceAccountToken: false
  annotations: {}
network:
  http:
    servicePort: 8080
#    serviceMonitor: {}
#    ingress:
#      host: application-test.chapp-test.os1.balgroupit.com
service:
  type: ClusterIP
  annotations: {}
ingress:
  controller: Route
env: []
envFrom: []
persistence:
  enabled: false
  accessModes: ReadWriteOnce
  storageClass: trident-nfs-snapshot
  annotations: {}
#  size: 1Gi
#  volumeMount: /var/app/data/
volumes: []
volumeMounts: []
readinessProbe: {}
#  httpGet:
#    path: /
#    port: http
livenessProbe: {}
#  httpGet:
#    path: /
#    port: http
resources: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
defaultAffinityRules:
  enabled: true
annotations: {}
command: []
args: []
initContainers: []
