replicaCount: 2
revisionHistoryLimit: 1
image:
  repository: registry.baloise.dev/example/nginx-sample
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
podSecurityContext: {}
securityContext: {}
serviceAccount:
  create: true
  name:
  automountServiceAccountToken: true
network:
  api:
    servicePort: 8080
    ingress:
      host: api.example.tld
  mgmt:
    servicePort: 9090
    ingress:
      host: app.example.tld
      annotations:
        haproxy.router.openshift.io/timeout: 5m
service:
  type: ClusterIP
  annotations:
    test: abc
deployment:
  strategy:
    type: Recreate
env:
  - name: DEMO_VARIABLE
    value: "Demo Variable"
envFrom: []
persistence:
  name: data
  storageClass: custom-storage-class
  enabled: true
  accessModes: ReadWriteMany
  size: 100Mi
  volumeMountPath: /app/data
volumes:
  - name: config-volume
    configMap:
      name: special-config
volumeMounts:
  - mountPath: /usr/local/sometool
    name: special-config
  - mountPath: /var/data
    name: data
readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 1
livenessProbe: {}
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 32Mi
tlsSidecar:
  enabled: true
  image:
    repository: docker.io/envoyproxy/envoy
    tag: v1.14.4
    pullPolicy: IfNotPresent
  upstreamPort: 8080
  httpsPort: 8443
  resources:
    requests:
      memory: 32Mi
      cpu: 20m
    limits:
      memory: 32Mi
      cpu: 100m
nodeSelector: {}
tolerations: []
affinity: {}
defaultAffinityRules: {}
annotations:
  sidecar.istio.io/inject: "true"
labels:
  maistra.io/expose-route: 'true'
command:
  - /app
  - --debug
args:
  - --port=123
  - --path=/a/b/c
