image:
  repository: quay.balgroupit.com/education/devops-stack-nginx-demo
  tag: ab3a925a155e0afa2513082350cedb8ece917650
  pullPolicy: IfNotPresent
externalSecret:
  addAsEnv: false
  mountPath:
  overrideName: mysecret
  refs:
    - vaultPath: secrets/apps/exampleApplication/T/exampleSecret
      vaultKey: key
      secretKey: secretKey
      addAsEnv: false
      mountPath: /file/path
    - vaultPath: secrets/apps/exampleApplication/T/exampleSecret
      vaultKey: key
      secretKey: secondSecretKey
      addAsEnv: true