replicaCount: 1

image:
#  repository: quay.balgroupit.com/example/nginx-sample
#  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

route:
  enabled: false
#  host: demo-app.chapp-test.os1.balgroupit.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
