replicaCount: 1
revisionHistoryLimit: 1
image:
#  repository: quay.balgroupit.com/example/nginx-sample
#  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
service:
  type: ClusterIP
  port: 8080
ingress:
  controller: Route
  enabled: false
#  host: demo-app.chapp-test.os1.balgroupit.com
#  zone: ch
  path: /
env: []
envFrom: []
persistence:
  enabled: false
  accessModes: ReadWriteOnce
  storageClass: trident-nfs-snapshot
#  size: 1Gi
#  volumeMount: /var/app/data/
volumes: []
volumeMounts: []
readinessProbe: {}
#  httpGet:
#    path: /
#    port: http
livenessProbe: {}
#  httpGet:
#    path: /
#    port: http
resources: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
defaultAffinityRules:
  enabled: true
annotations: {}