replicaCount: 1
revisionHistoryLimit: 1
image:
#  repository: registry.baloise.dev/example/nginx-sample
#  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
service:
  type: ClusterIP
ports:
  http:
    servicePort: 80
    containerPort: 8080
ingress:
  controller: Route
  enabled: false
  annotations: {}
  #  host: demo-app.apps.example.tld
  path: /
env: []
envFrom: []
persistence:
  enabled: false
  accessModes: ReadWriteOnce
#  storageClass: ""
#  size: 1Gi
#  volumeMount: /var/app/data/
volumes: []
volumeMounts: []
readinessProbe: {}
#  httpGet:
#    path: /
#    port: http
livenessProbe: {}
#  httpGet:
#    path: /
#    port: http
resources: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
defaultAffinityRules:
  enabled: true
annotations: {}