app:
  replicaCount: 2
  revisionHistoryLimit: 1
  image:
    repository: example/nginx-sample
    tag: latest
    pullPolicy: IfNotPresent
  network:
    http:
      servicePort: 8080
      ingress:
        host: example.org
  readinessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 5
    timeoutSeconds: 1
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 200m
      memory: 32Mi
