{{- if gt (len .Values.externalSecret.refsFrom) 0 }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "generic-chart.externalSecretName" $ }}-refs-from
  labels:
    {{- include "generic-chart.labels" $ | nindent 4 }}
  annotations: {{- toYaml .Values.externalSecret.annotations | nindent 4 }}
spec:
  secretStoreRef: {{- toYaml .Values.externalSecret.secretStoreRef | nindent 4 }}
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
  {{- range $refFrom := $.Values.externalSecret.refsFrom }}
    - extract:
        key: {{ $refFrom.vaultPath }}
  {{- end }}
{{- end }}