{{- if .Values.externalSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "generic-chart.externalSecretName" $ }}
  labels: {{- include "generic-chart.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Validate=false # can be removed when validate=false is true for Argo CD apps
spec:
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  {{- range $ref := $.Values.externalSecret.refs }}
    - remoteRef:
        key: {{ $ref.vaultPath }}
        property: {{ $ref.vaultKey }}
      secretKey: {{ $ref.secretKey }}
  {{- end }}
{{- end }}