{{- if gt (len .Values.externalSecret.refs) 0 }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "generic-chart.externalSecretName" $ }}
  labels:
    {{- include "generic-chart.labels" $ | nindent 4 }}
  annotations: {{- toYaml .Values.externalSecret.annotations | nindent 4 }}
spec:
  secretStoreRef: {{- toYaml .Values.externalSecret.secretStoreRef | nindent 4 }}
  target: {{- toYaml .Values.externalSecret.target | nindent 4 }}
  data:
  {{- range $ref := $.Values.externalSecret.refs }}
    - remoteRef:
        key: {{ $ref.vaultPath }}
        property: {{ $ref.vaultKey }}
      secretKey: {{ default $ref.vaultKey $ref.secretKey }}
  {{- end }}
{{- end }}