{{ if and (.Values.network) (eq "Route" .Values.ingress.controller) }}
{{- range $key, $val := .Values.network }}
{{- if not (kindIs "invalid" $val.ingress) }}
{{- $defaultTermination :="edge" }}
{{- if $.Values.tlsSidecar.enabled }}
{{- $defaultTermination = "reencrypt" }}
{{- end }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
{{ include "generic-chart.labels" $ | indent 4 }}
  name: {{ printf "%s-%s" (include "generic-chart.name" $ ) $key }}
{{- if $val.ingress.annotations }}
  annotations:
    {{- toYaml $val.ingress.annotations | nindent 4 }}
{{- end }}
spec:
  host: {{ $val.ingress.host }}
  path: {{ default "/" $val.ingress.path }}
  port:
    targetPort: {{ $key }}    
  tls:
    insecureEdgeTerminationPolicy: {{ default "Redirect" $val.ingress.insecureEdgeTerminationPolicy }}
    termination: {{ default $defaultTermination $val.ingress.termination }}
  to:
    kind: Service
    name: {{ include "generic-chart.name" $ }}
    weight: 100
  wildcardPolicy: None
{{ end }}
{{- end }}
{{- end }}