{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {{- include "generic-chart.labels" . | nindent 4 }}
  annotations: {{- if gt (len .Values.persistence.annotations) 0 }}{{- toYaml .Values.persistence.annotations | nindent 4 }}{{- end }}
  name: {{ default ( include "generic-chart.name" . ) .Values.persistence.name }}
  namespace: {{ template "generic-chart.namespace" $ }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass}}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{ end -}}
{{ end -}}