{{ if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
{{ include "generic-chart.labels" . | indent 4 }}
  name: {{ include "generic-chart.name" . }}
spec:
  host: {{ include "generic-chart.host" . }}
  path: {{ .Values.route.path }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "generic-chart.name" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
