{{ if .Values.network }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-chart.name" . }}
  labels:
{{ include "generic-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:  
  {{- range $key, $val := .Values.network }}
  - name: {{ $key }}    
    port: {{ required "Please enter a valid port! " $val.servicePort }}
    protocol: {{ default "TCP" $val.protocol }}
    targetPort: {{ default $key $val.targetPort}} 
  {{- end}}

  selector:
    app: {{ include "generic-chart.name" . }}
    release: {{ .Release.Name }}
{{- end}}