{{ if .Values.service.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-chart.name" . }}
  labels:
{{ include "generic-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:  
  {{- range $key, $val := .Values.service.ports }}
  - name: {{ $key }}
    {{- $name := default "http" $key }}
    port: {{ required "Please enter a valid port! " $val.port }}
    protocol: {{ default "TCP" $val.protocol }}
    targetPort: {{ default $name $val.targetPort}} 
  {{- end}}

  selector:
    app: {{ include "generic-chart.name" . }}
    release: {{ .Release.Name }}
{{- end}}