{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "generic-chart.name" .) .Values.serviceAccount.name }}
  namespace: {{ template "generic-chart.namespace" $ }}
  labels: {{- include "generic-chart.labels" . | nindent 4 }}
  annotations: {{- if gt (len .Values.serviceAccount.annotations) 0 }}{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}{{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}