{{ if .Values.metrics }}
{{ if .Values.network }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "generic-chart.name" . }}-servicemonitor
  labels:
{{ include "generic-chart.labels" . | indent 4 }}
spec:
  endpoints:
    - interval: {{ default "30s" .Values.metrics.interval }}
      port: {{ default .Values.network.http.servicePort .Values.metrics.port }}
      path: {{ default "/metrics" .Values.metrics.path }}
      scheme: {{ default "http" .Values.metrics.scheme }}
  selector:
    matchLabels:
      app: {{ include "generic-chart.name" . }}
{{- end }}
{{- end }}
