apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-chart.name" . }}
  labels:
{{ include "generic-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "generic-chart.name" . }}
    release: {{ .Release.Name }}
