{{ if .Values.serviceMonitor }}
{{ if .Values.network }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "generic-chart.name" . }}-servicemonitor
  labels:
{{ include "generic-chart.labels" . | indent 4 }}
spec:
  endpoints:
    - interval: {{ default "30s" .Values.serviceMonitor.interval }}
      port: {{ default "http" .Values.serviceMonitor.port | quote }}
      path: {{ default "/metrics" .Values.serviceMonitor.path }}
      scheme: {{ default "http" .Values.serviceMonitor.scheme }}
  selector:
    matchLabels:
      app: {{ include "generic-chart.name" . }}
{{- end }}
{{- end }}
