{{ if and (and .Values.network .Values.deployment.stateful.enabled) .Values.deployment.stateful.servicePerPod }}
  {{- range $i, $e := until (.Values.replicaCount | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-chart.name" $ }}-{{ $i }}
  namespace: {{ template "generic-chart.namespace" $ }}
  labels: {{ include "generic-chart.labels" $ | nindent 4 }}
  annotations: {{- if gt (len $.Values.service.annotations) 0 }}{{- toYaml $.Values.service.annotations | nindent 4 }}{{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
  {{- range $key, $val := $.Values.network }}
    {{- if $val.servicePort}}
  - name: {{ $key }}    
    port: {{ $val.servicePort }}
    protocol: {{ default "TCP" $val.protocol }}
    targetPort: {{ default $key $val.targetPort }}
    {{- end }}
  {{- end }}
  selector:
    app: {{ include "generic-chart.name" $ }}
    release: {{ $.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ include "generic-chart.name" $ }}-{{ $i }}
  {{- end }}
{{- end }}