{{- if .Values.enableServiceMesh }}
  {{- range $key, $val := .Values.network }}
    {{- if not ( $val.ingress.enableIstioIngressGateway ) }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s" (include "generic-chart.name" $) }}
  namespace: {{ template "generic-chart.namespace" $ }}
  labels: {{- include "generic-chart.labels" $ | nindent 4 }}
spec:
  hosts:
  - {{ printf "%s" (include "generic-chart.name" $) }}
  http:
  - route:
    - destination:
        host: {{ printf "%s" (include "generic-chart.name" $) }}
        port:
          number: {{ $val.servicePort }}
    {{- end }}
  {{- end }}
{{- end }}
