{{- if .Values.enableServiceMesh }}
{{- range $key, $val := .Values.network }}
{{- if not ( $val.enableIstioIngressGateway ) }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s" (include "generic-chart.name" $) }}
  labels:
{{ include "generic-chart.labels" $ | indent 4 }}
spec:
  hosts:
  - {{ printf "%s" (include "generic-chart.name" $) }}
  http:
  - route:
    - destination:
        host: {{ printf "%s" (include "generic-chart.name" $) }}
        port:
          number: {{ $val.servicePort }}
{{- end }}
{{- end }}
{{- end }}
